language: android
jdk: oraclejdk8
env:
  global:
    - ANDROID_TARGET=android-15
    - ANDROID_ABI=armeabi-v7a
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.0
  - android-25
  - extra-android-m2repository
  - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}
   licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+
before_install:
 - rvm install 2.0.0
before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
 directories:
 - ~/.android
 - $HOME/.gradle/caches/
 - $HOME/.gradle/wrapper/
script:
 - scripts/saddler.sh
after_script:
 - mkdir -p $TRAVIS_BUILD_DIR/junit/
 - find . -type d -regex ".*/reports/tests$" -exec cp -r {} $TRAVIS_BUILD_DIR/junit/ \;

